[tool.poetry]
name = "splash-bot"
version = "3.0"
description = "A discord bot for me and my friends"
authors = ["Tibor309 <<tibormercs8@gmail.com>>"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.4"
Flask = "^2.0.1"
praw = "^7.4.0"
discord-together = "^1.2.1"
youtube_dl = "^2021.6.6"
PyNaCl = "^1.4.0"
discord = "^1.7.3"
"dislash.py" = "^1.4.9"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
