[tool.poetry]
name = "splash-bot"
version = "4.1"
description = "A discord bot for me and my friends"
authors = ["Tibor309 <<tibormercs8@gmail.com>>"]
exclude = ["discord", "discord.py"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.4"
Flask = "^2.0.1"
praw = "^7.4.0"
PyNaCl = "^1.4.0"
py-cpuinfo = "^8.0.0"
discord = "^1.7.3"
py-cord = {git = "https://github.com/Pycord-Development/pycord"}
discord-together = "^1.2.4"
psutil = "^5.9.1"
python-dotenv = "^0.20.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
